### PR TITLE
feat: Prefab, Duplication and naming overhaul

### PR DESCRIPTION
**Pull request by Strackeror**
Alright, this is a big one:

This is a wide overhaul of the handling of map objects concerning names and fields that reference other map objects.
It's also a pretty complete rewrite of the prefabs to take that into account and simplify their handling.

The general idea is to be able to keep references correct through those operations, as much as possible. That means:
Renaming a map object also modifies every single reference to it, including on itself. This does mean that renaming needs a button to commit the changes now (and the change will be prevented if it would result in duplicate names)

Duplicating an object will keep every reference that's still available after the dupe, this mostly means that references to other objects will be emptied out if the dupe goes to another map.

Duplicating multiple objects will correctly modify references to other duplicated objects, so for example if we duplicate both `Treasure` and `ItemPart` in this example:
image

The new `Treasure` will point to the new `ItemPart`!
image

The same logic applies to prefabs ! If we prefab multiple objects and they have references to each other, those will be restored once we load the prefab again, but other references will be automatically emptied out.

Finally, I consolidated all the prefab tools to their own window, which I think works really well !
image

I'm putting this as a draft for two reasons:
- This is a pretty huge change, I'm aware, so I'm very open to feedback and may have forgotten some details
- This... needs more testing, I'll try and work with it for a few days to see if I missed anything, but I mostly work with Elden Ring. It should be pretty generic, but the devil is in the details

### CODE REVIEW

**Comment by vawser** [comment]
Looks good. I will go through and test the changes with each project type to scout for any oversights.

**Comment by vawser** [comment]
I did notice there were a few issues with some map object types, but they seem related to the MSB implementation and are the same with the current implementation so it doesn't matter for now. 

It would be great if BTL.Light was supported too.

Any how, once you are ready for it to be merged, undraft it and I'll merge it in.

**Comment by Strackeror** [comment]
Alright, yeah haven't found any big issues either, I tweaked the UI a bit, but this should be at least relatively good to go !

**Comment by vawser** [comment]
Sorry, I've had to revert this PR as there were some issues and I don't want to regress Map Editor functionality:
- The "Rename" button is a bit of a workflow blocker, having to press it to change a name is a regression from the previous behavior where you could freely edit the name field.
- The renaming doesn't respect the 4 digits at the end of several map objects (such as c4690_9000, 9000 should match the instance ID), it instead applies a number wrapped with {}. This is a regression to the previous behavior that handled this correctly.

If those issues are fixed, make a new PR with the fixed code and I'll merge the changes back in.

**Comment by Strackeror** [comment]
Hey, alright i'll look into it ! I'd like to have your opinion on a few things first, since both of those were conscious changes, not accidents. (Maybe I should have put more focus on them in the PR, sorry about that)

For the renaming indices, it's a bit ambiguous, since the {} this is the naming schemes soulsformats uses for duplicates (and indeed the extra {} part will be stripped in the actual data), but yeah I could see the `_instanceId` being less surprising.

The renaming button is a harder problem to solve. The idea behind it was to make renames act more intuitively, and not breaking references to an object just by renaming it. The problem is that it makes the act of renaming fallible, since you do not want duplicate names in your map, that makes cross references ambiguous, and that's kind of impossible to avoid if your text input is a direct map to the string.

**Pull request merged**
