### PR TITLE
Add eng-zhs double language support almost 90%

### PR DESCRIPTION
**Pull request by Lioncky**
I've made a copy for Chinese, most of us can't use it fluently.

### CODE REVIEW

**Comment by vawser** [comment]
This won't be merged. Having mixed English/Chinese localization isn't a solution to providing readability for Chinese users.
Rather, you should maintain a fork of Smithbox with the changes.

**Comment by Lioncky** [comment]
Yes, double language is unfriendly for eng users, and chs users alwasys watch eng-zhs movie. 

> "... maintain a fork of Smithbox with the changes."
> ImGui is not good for this, need a solution, as you say big task, but necessory.

**Comment by vawser** [comment]
I am working on adding proper localization, where the user can switch between languages and Smithbox itself supports it. Once that is done, I would appreciate a Chinese translation.

**Comment by Lioncky** [comment]
Yep, then you can cantain me at anytime I'll translate. 
By the way, I've noticed you change the export FMGs to json, it's good for eng, but "\uXXXX\uXXXX" for other hieroglyph language, I prefer the old, you can make a switch for that

**Pull request closed without merging**
